import { ClerkProvider } from '@clerk/nextjs';
import { GeistSans } from "geist/font/sans";
import NavBar from "~/app/_components/topnav";
import "~/styles/globals.css";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="w-full">
          <NavBar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
